/*
	SIC LABORATORY, LG ELECTRONICS INC., SEOUL, KOREA
	Copyright(c) 2010 by LG Electronics Inc.

	This program is free software; you can redistribute it and/or 
	modify it under the terms of the GNU General Public License
	version 2 as published by the Free Software Foundation.

	This program is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of 
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
	GNU General Public License for more details.
*/ 

#ifndef __ADEC_MODULE_SE_PARAM_MAP_H__
#define __ADEC_MODULE_SE_PARAM_MAP_H__


// SE param memory map 에 따라서 변동 되어야 함. 
#define NUM_OF_BASIC_PARAM				3

#define NUM_OF_LGSEFN000_INIT_PARAM		309	  
#define NUM_OF_LGSEFN000_VAR_PARAM 		1

#define NUM_OF_LGSEFN013_INIT_PARAM		5	  
#define NUM_OF_LGSEFN013_VAR_PARAM 		0

#define NUM_OF_LGSEFN001_INIT_PARAM		0	  
#define NUM_OF_LGSEFN001_VAR_PARAM 		325

#define NUM_OF_LGSEFN012_INIT_PARAM		4	  
#define NUM_OF_LGSEFN012_VAR_PARAM 		2

#define NUM_OF_LGSEFN003_INIT_PARAM		330	  
#define NUM_OF_LGSEFN003_VAR_PARAM 		0

#define NUM_OF_LGSEFN004MODE1_INIT_PARAM    0	  
#define NUM_OF_LGSEFN004MODE1_VAR_PARAM 	27

#define NUM_OF_LGSEFN004MODE2_INIT_PARAM	0	  
#define NUM_OF_LGSEFN004MODE2_VAR_PARAM 	15

#define NUM_OF_LGSEFN004MODE3_INIT_PARAM	0	  
#define NUM_OF_LGSEFN004MODE3_VAR_PARAM 	25

#define NUM_OF_LGSEFN006_INIT_PARAM		0	  
#define NUM_OF_LGSEFN006_VAR_PARAM 		10

#define NUM_OF_LGSEFN008_INIT_PARAM		119	  
#define NUM_OF_LGSEFN008_VAR_PARAM 		7

#define NUM_OF_LGSEFN009_INIT_PARAM		2	  
#define NUM_OF_LGSEFN009_VAR_PARAM 		2

#define NUM_OF_LGSEFN010_INIT_PARAM		10	  
#define NUM_OF_LGSEFN010_VAR_PARAM 		0

#define NUM_OF_LGSEFN011_INIT_PARAM		3	  
#define NUM_OF_LGSEFN011_VAR_PARAM 		66


#define NUM_OF_LGSEFN014_INIT_PARAM		71	  
#define NUM_OF_LGSEFN014_VAR_PARAM 		0


#define ADDR_OF_LGSEFN000	(NUM_OF_BASIC_PARAM)
#define ADDR_OF_LGSEFN013	(ADDR_OF_LGSEFN000 + NUM_OF_LGSEFN000_INIT_PARAM + NUM_OF_LGSEFN000_VAR_PARAM)
#define ADDR_OF_LGSEFN001	(ADDR_OF_LGSEFN013 + NUM_OF_LGSEFN013_INIT_PARAM + NUM_OF_LGSEFN013_VAR_PARAM)
#define ADDR_OF_LGSEFN012	(ADDR_OF_LGSEFN001 + NUM_OF_LGSEFN001_INIT_PARAM + NUM_OF_LGSEFN001_VAR_PARAM)
#define ADDR_OF_LGSEFN003	(ADDR_OF_LGSEFN012 + NUM_OF_LGSEFN012_INIT_PARAM + NUM_OF_LGSEFN012_VAR_PARAM)
#define ADDR_OF_LGSEFN004MODE1	(ADDR_OF_LGSEFN003 + NUM_OF_LGSEFN003_INIT_PARAM + NUM_OF_LGSEFN003_VAR_PARAM)
#define ADDR_OF_LGSEFN004MODE2	(ADDR_OF_LGSEFN004MODE1 + NUM_OF_LGSEFN004MODE1_INIT_PARAM + NUM_OF_LGSEFN004MODE1_VAR_PARAM)
#define ADDR_OF_LGSEFN004MODE3	(ADDR_OF_LGSEFN004MODE2 + NUM_OF_LGSEFN004MODE2_INIT_PARAM + NUM_OF_LGSEFN004MODE2_VAR_PARAM)
#define ADDR_OF_LGSEFN006	(ADDR_OF_LGSEFN004MODE3 + NUM_OF_LGSEFN004MODE3_INIT_PARAM + NUM_OF_LGSEFN004MODE3_VAR_PARAM)
#define ADDR_OF_LGSEFN008	(ADDR_OF_LGSEFN006 + NUM_OF_LGSEFN006_INIT_PARAM + NUM_OF_LGSEFN006_VAR_PARAM)
#define ADDR_OF_LGSEFN009	(ADDR_OF_LGSEFN008 + NUM_OF_LGSEFN008_INIT_PARAM + NUM_OF_LGSEFN008_VAR_PARAM)
#define ADDR_OF_LGSEFN010	(ADDR_OF_LGSEFN009 + NUM_OF_LGSEFN009_INIT_PARAM + NUM_OF_LGSEFN009_VAR_PARAM)
#define ADDR_OF_LGSEFN011	(ADDR_OF_LGSEFN010 + NUM_OF_LGSEFN010_INIT_PARAM + NUM_OF_LGSEFN010_VAR_PARAM)
#define ADDR_OF_LGSEFN014	(ADDR_OF_LGSEFN011 + NUM_OF_LGSEFN011_INIT_PARAM + NUM_OF_LGSEFN011_VAR_PARAM)







typedef enum
{
	AUD_SE_FN000,				// 0
	AUD_SE_FN001,				// 1
	AUD_SE_FN002,				// 2
	AUD_SE_FN003,				// 3
	AUD_SE_FN004_MODE1,		// 4
	AUD_SE_FN004_MODE2,		// 5
	AUD_SE_FN004_MODE3,		// 6
	AUD_SE_FN005,				// 7
	AUD_SE_FN006,				// 8
	AUD_SE_FN007,				// 9
	AUD_SE_FN008,				// 10
	AUD_SE_FN009,				// 11
	AUD_SE_FN010,				// 12
	AUD_SE_FN011,				// 13
	AUD_SE_FN012,				// 14
	AUD_SE_FN013,				// 15
	AUD_SE_FN014,				// 16
	AUD_SE_FN_MAX,			// 17
	AUD_SE_FN_UPDATE_PARAM	= 30	, // 30
}AUD_SE_FN_MODE_T;









/////////////////////////////////////////////////////////////////
#define NUM_OF_SDV_INIT_PARAM		NUM_OF_LGSEFN000_INIT_PARAM			  
#define NUM_OF_SDV_VAR_PARAM		NUM_OF_LGSEFN000_VAR_PARAM 		

#define NUM_OF_AGCN_INIT_PARAM		NUM_OF_LGSEFN013_INIT_PARAM			  
#define NUM_OF_AGCN_VAR_PARAM		NUM_OF_LGSEFN013_VAR_PARAM 		

#define NUM_OF_AGC_INIT_PARAM		NUM_OF_LGSEFN001_INIT_PARAM			  
#define NUM_OF_AGC_VAR_PARAM		NUM_OF_LGSEFN001_VAR_PARAM 		

#define NUM_OF_AGCCI_INIT_PARAM		NUM_OF_LGSEFN012_INIT_PARAM			  
#define NUM_OF_AGCCI_VAR_PARAM		NUM_OF_LGSEFN012_VAR_PARAM 		

#define NUM_OF_DEQ_INIT_PARAM 		NUM_OF_LGSEFN003_INIT_PARAM			  
#define NUM_OF_DEQ_VAR_PARAM		NUM_OF_LGSEFN003_VAR_PARAM 		

#define NUM_OF_PEQMODE1_INIT_PARAM	NUM_OF_LGSEFN004MODE1_INIT_PARAM			  
#define NUM_OF_PEQMODE1_VAR_PARAM	NUM_OF_LGSEFN004MODE1_VAR_PARAM 		

#define NUM_OF_PEQMODE2_INIT_PARAM	NUM_OF_LGSEFN004MODE2_INIT_PARAM			  
#define NUM_OF_PEQMODE2_VAR_PARAM	NUM_OF_LGSEFN004MODE2_VAR_PARAM 		

#define NUM_OF_PEQMODE3_INIT_PARAM	NUM_OF_LGSEFN004MODE3_INIT_PARAM			  
#define NUM_OF_PEQMODE3_VAR_PARAM	NUM_OF_LGSEFN004MODE3_VAR_PARAM 		


#define NUM_OF_INFSND_INIT_PARAM	NUM_OF_LGSEFN006_INIT_PARAM			  
#define NUM_OF_INFSND_VAR_PARAM		NUM_OF_LGSEFN006_VAR_PARAM 		

#define NUM_OF_HC_INIT_PARAM		NUM_OF_LGSEFN008_INIT_PARAM			  
#define NUM_OF_HC_VAR_PARAM			NUM_OF_LGSEFN008_VAR_PARAM 		

#define NUM_OF_VOL_INIT_PARAM		NUM_OF_LGSEFN009_INIT_PARAM			  
#define NUM_OF_VOL_VAR_PARAM		NUM_OF_LGSEFN009_VAR_PARAM 		

#define NUM_OF_INCHECK_INIT_PARAM	NUM_OF_LGSEFN010_INIT_PARAM			  
#define NUM_OF_INCHECK_VAR_PARAM	NUM_OF_LGSEFN010_VAR_PARAM 		

#define NUM_OF_EME_INIT_PARAM		NUM_OF_LGSEFN011_INIT_PARAM			  
#define NUM_OF_EME_VAR_PARAM		NUM_OF_LGSEFN011_VAR_PARAM 		

#define NUM_OF_ASC_INIT_PARAM		NUM_OF_LGSEFN014_INIT_PARAM			  
#define NUM_OF_ASC_VAR_PARAM		NUM_OF_LGSEFN014_VAR_PARAM 		


#define ADDR_OF_SDV				ADDR_OF_LGSEFN000	
#define ADDR_OF_AGCN			ADDR_OF_LGSEFN013	
#define ADDR_OF_AGC				ADDR_OF_LGSEFN001	
#define ADDR_OF_AGCCI			ADDR_OF_LGSEFN012	
#define ADDR_OF_DEQ				ADDR_OF_LGSEFN003	
#define ADDR_OF_PEQMODE1		ADDR_OF_LGSEFN004MODE1	
#define ADDR_OF_PEQMODE2        ADDR_OF_LGSEFN004MODE2	
#define ADDR_OF_PEQMODE3		ADDR_OF_LGSEFN004MODE3	
#define ADDR_OF_INFSND			ADDR_OF_LGSEFN006	
#define ADDR_OF_HC				ADDR_OF_LGSEFN008	
#define ADDR_OF_VOL				ADDR_OF_LGSEFN009	
#define ADDR_OF_INCHECK			ADDR_OF_LGSEFN010	
#define ADDR_OF_EME				ADDR_OF_LGSEFN011	
#define ADDR_OF_ASC				ADDR_OF_LGSEFN014	


#endif
